baseURL = "http://example.org/"
languageCode = "en-us"
title = "Mothership - Documentation"

theme = "hugo-theme-learn"

[params]
themeVariant = "mothership"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/spicket/mothership-documentation"
weight = 10